### ISSUE TITLE
Test are failing on Node.js > 10

### ISSUE THREAD

**Issue by mojoaxel** [svg-sprite/svg-sprite#302] opened 2019-12-02 10:34 UTC
I have two failing test in the current master (304a347f472429f7b1fc6dcca2eef6b32861fbc0):

- svg-sprite | with minimum configuration and 11 SVG files | in «css» mode and all render types | enabled | creates visually correct sprite with | packed layout
- svg-sprite | with minimum configuration and 11 SVG files | in «view» mode | creates visually correct sprite with | packed layout

#### expected
![image](https://user-images.githubusercontent.com/600565/69947826-c3532700-14ee-11ea-9f6f-2cc48f97cf6c.png)

#### current
![image](https://user-images.githubusercontent.com/600565/69947870-d960e780-14ee-11ea-9dac-051d942d7db2.png)

- OS: Ubuntu Linux 64 18.04
- node: v11.15.0
- npm: 6.13.0

**Comment by XhmikosR** [comment] 2021-02-22 15:54
I recently spent some time with svg-sprite and for some reason, Node.js > 10 generates a different image. The order seems different.

If you pinpoint the root cause please let me know. In the meantime, I added a different image for Node.js > 10, but that's for making CI happy since I don't know the root cause either. #378

**Comment by XhmikosR** [comment] 2021-02-24 15:38
Do you hit this issue in your puppeteer branch too?

The order seems to change starting from Node.js 12 and on.

**Comment by XhmikosR** [comment] 2021-02-28 17:30
@mojoaxel please see the discussion in https://github.com/svg-sprite/svg-sprite/pull/398#issuecomment-787477660

Maybe you can figure out a fix faster :)

**Comment by XhmikosR** [comment] 2021-02-28 19:09
Merged #398 so this should work on non-Windows machines.

**Closed by XhmikosR** 2021-02-28 19:09 UTC
