### ISSUE TITLE
bug: 2.0.0: `shape.id.separator` does not produce an `id` with the parent directory names

### ISSUE THREAD

**Issue by artuska** [svg-sprite/svg-sprite#740] opened 2022-10-13 14:24 UTC
In 1.5.0 `shape.id.separator` traversed full directory path + file name into the shape ID. Now in 2.0.0 shape ID is always a svg file name, without any parent folders.

**Comment by Kreeg** [comment] 2022-10-26 11:45
@artuska hello!
Can you provide some examples? It'll be great if you provide a new corresponding failing test case in `test/svg-sprite/shape`.

**Comment by sfe-efficy** [comment] 2022-10-29 10:36
Hi, the problem is related with the change in shape.js line 150:

In version 1.5.4 it was:
https://github.com/svg-sprite/svg-sprite/blob/v1.5.4/lib/svg-sprite/shape.js#L150

(It was getting the difference between the full path to the file and the path used to search files).

And now in version 2.0:

[[It's getting th]()](https://github.com/svg-sprite/svg-sprite/blob/v2.0.0/lib/svg-sprite/shape.js#L151)

It's getting the name of the full path:

![image](https://user-images.githubusercontent.com/95854297/198826484-56a82210-811b-4e2e-92dd-765a0970e22b.png)

![image](https://user-images.githubusercontent.com/95854297/198826491-404ea728-b1f9-48ea-93bb-52b4c785add1.png)

Before:

![image](https://user-images.githubusercontent.com/95854297/198826523-1d0d1570-9ebb-4ed9-83c4-fc119ca48a21.png)

And the code in the createIdGenerator (not changed), at line 41, it's waiting a relative path (it's also explined in the variable comment).
https://github.com/svg-sprite/svg-sprite/blob/v1.5.4/lib/svg-sprite/shape.js#L33
https://github.com/svg-sprite/svg-sprite/blob/v2.0.0/lib/svg-sprite/shape.js#L33

So, it can restore the previous line, or comparing the directory full path with the directory base path used to search with path.relative:

![image](https://user-images.githubusercontent.com/95854297/198826651-f2c55891-5f7b-4b43-8299-e27827e3a1b5.png)

And the ID generated is going to have the expected value:

![image](https://user-images.githubusercontent.com/95854297/198826732-aa9d308e-1c71-4770-a1d7-b9547d0d841d.png)

**Comment by XhmikosR** [comment] 2022-10-31 16:26
Released in [v2.0.1](https://github.com/svg-sprite/svg-sprite/releases/tag/v2.0.1)

**Comment by egorkel-altexsoft** [comment] 2022-11-08 11:58
The issue is not solved.
`file.base` is calculated incorrectly here https://github.com/svg-sprite/svg-sprite/blob/main/lib/svg-sprite.js#L128

![image](https://user-images.githubusercontent.com/95917278/200558014-cea15be0-97e0-4e9c-891c-431bac801745.png)

Compare with https://github.com/svg-sprite/svg-sprite/blob/v1.5.4/lib/svg-sprite.js#L131

![image](https://user-images.githubusercontent.com/95917278/200558183-7ccd20e7-8713-4ff7-813d-e0e9a045d3b3.png)

**Comment by sfe-efficy** [comment] 2022-11-08 12:42
why did you considere that the bug persists?

The only different between previous code and this one is related with the final directory separtor.

The previous code was keeping a final separator. Now not.
In both cases are ok when it's using path.resolve and setting the file.base.

![image](https://user-images.githubusercontent.com/95854297/200566392-fa8679ac-b23f-45f4-b66d-4689fd648fed.png)

**Comment by egorkel-altexsoft** [comment] 2022-11-08 13:43
In my case here https://github.com/svg-sprite/svg-sprite/blob/main/lib/svg-sprite.js#L83

`file` is `/home/egor/projects/yourapp-uikit-web/libs/ui-kit/src/lib/icons/svg-icons/eva/line/info.svg`

`name` is `eva/line/info.svg`

**Comment by XhmikosR** [comment] 2022-11-08 14:52
Sounds like e85b53c6343dd78d1a5eccae137e2b337be94a5a is to blame. Can someone who's having this issue try it with:

```sh
npm i github:svg-sprite/svg-sprite#2.x
```

I thought this was covered by the tests but maybe it slipped through.

**Comment by egorkel-altexsoft** [comment] 2022-11-08 14:57
> Sounds like [e85b53c](https://github.com/svg-sprite/svg-sprite/commit/e85b53c6343dd78d1a5eccae137e2b337be94a5a) is to blame. Can someone who's having this issue try it with:
> 
> ```shell
> npm i github:svg-sprite/svg-sprite#2.x
> ```
> 
> I thought this was covered by the tests but maybe it slipped through.

I can confirm that this version works as expected

**Comment by XhmikosR** [comment] 2022-11-08 15:02
@egorkel-altexsoft can you try one more time please? I tried with a different approach.

BTW if someone wants to submit a test case, that would make sure we don't hit this again in the future and is more than welcome.

**Comment by egorkel-altexsoft** [comment] 2022-11-08 15:07
Nope, it doesn't work
`libs--ui-kit--src--lib--icons--svg-icons--eva--line--info`

**Comment by egorkel-altexsoft** [comment] 2022-11-08 15:10
No problem

**Comment by sfe-efficy** [comment] 2022-11-08 21:50
when I was checking the first time this problem, I was using gulp-svg-sprite.

https://github.com/svg-sprite/svg-sprite/blob/main/lib/svg-sprite.js#L83
In the that method from gulp-svg-sprite is receiving directly a File object with this information:

![image](https://user-images.githubusercontent.com/95854297/200682546-223d8c72-d1a6-42d9-96c7-46059123a7eb.png)

With "base" property that contains the source folder:

![image](https://user-images.githubusercontent.com/95854297/200682833-1336e6b2-1739-4d3e-a100-0a0f5486b6cc.png)

path: with the full path, and so on.

But, now checking with the bin script file like @egorkel-altexsoft is using, I'm having the same problem.
But, this problems happens inside of the file object created here https://github.com/svg-sprite/svg-sprite/blob/main/lib/svg-sprite.js#L127

![image](https://user-images.githubusercontent.com/95854297/200683152-8fee6516-b7b5-4b1a-942b-8a0e19169f4d.png)

With my configuration:

![image](https://user-images.githubusercontent.com/95854297/200683229-85e3b3ae-8ded-4a34-bec0-beb51c76716f.png)

**Comment by XhmikosR** [comment] 2022-11-12 16:05
Released in [v2.0.2](https://github.com/svg-sprite/svg-sprite/releases/tag/v2.0.2)

**Comment by kan-erik** [comment] 2022-11-25 10:49
I just wanted to add that this didn't work for me if the glob-pattern does not contain the "./" in the beginning.

Does not work:

`path/to/somefolder/**/*.svg`

Does work:

`path/to/somefolder/./**/*.svg`

**Comment by XhmikosR** [comment] 2022-11-25 16:25
Unless someone provides a patch with proper tests, I'm not sure how all these issues can be safely fixed... The code now should be what's used in 1.5.x too.

**Comment by XhmikosR** [comment] 2023-03-13 19:49
@Kreeg I think this is the only regression blocking us for v3.0.0 stable. Last time I had a look at it, I could fix the issue myself so any help is welcome.

**Comment by Kreeg** [comment] 2023-04-14 16:38
Possible cause: https://github.com/svg-sprite/svg-sprite/issues/220 ([commit](https://github.com/svg-sprite/svg-sprite/commit/14df65a086ff177bf80a2d9fd0aa07af9449dc4a)).
Possible fix: https://github.com/svg-sprite/svg-sprite/pull/804

**Comment by Kreeg** [comment] 2023-04-15 20:54
@kan-erik https://github.com/svg-sprite/svg-sprite/blob/main/docs/command-line.md#advanced-globbing

I'm closing this, because this feature is covered in docs

**Closed by Kreeg** 2023-04-15 20:54 UTC
Labels: bug, help-wanted
